<a href="https://colab.research.google.com/github/Arnav8055singh/ML-DL-python-/blob/main/3_1_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python


Advantages in Numpy Arrays:
1.Allows Several Mathematical Operations
2.Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Take

In [2]:
from time import process_time

time taken by a list

In [9]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015027419999995573


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5  # np_array = np_array + 5

end_time =  process_time()

print(end_time - start_time)


0.0016774030000004103


Numpy Arrays

In [12]:
#list

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
#creating a 1 dimensional array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [16]:
a.shape

(5,)

In [19]:
b = np.array([(1,3,6,9,11),(2,4,6,8,10)])
print(b)

[[ 1  3  6  9 11]
 [ 2  4  6  8 10]]


In [20]:
b.shape

(2, 5)

In [30]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #dtype = char , bool , float , int
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial PlaceHolders in numpy Array

In [22]:
#create a numpy array of Zeros

x = np.zeros([4,5])
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#create a numpy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
#array of a particular value

z = np.full([5,4],5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [34]:
# create an identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
#create a numpy array with random values

b = np.random.random([3,4])
print(b)

[[0.81155969 0.43651559 0.17696767 0.4686857 ]
 [0.98948865 0.84783437 0.41668342 0.37971035]
 [0.57745578 0.06802705 0.61022428 0.25842157]]


In [37]:
# random integer value arrays within a specific range

c = np.random.randint(10,100,(3,5))
print(c)

[[73 67 63 76 41]
 [92 11 28 36 35]
 [51 44 51 44 49]]


In [42]:
# array of evenly spaced values  --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [46]:
#array of evenly spaced values --> specifying the step

e = np.arange(10,30,9)
print(e)

[10 19 28]


In [47]:
#convert a list to a numpy array

list2 = [10, 20, 30, 40, 50]

np_array = np.asarray(list2)   #np.asarray converts one particular data type to numpy
print(np_array)
type(np_array)


[10 20 30 40 50]


numpy.ndarray

Analysing a numpy Array

In [48]:
c = np.random.randint(10,90,(5,5))
print(c)

[[69 61 19 12 79]
 [14 54 26 18 25]
 [84 49 10 49 32]
 [32 74 34 88 74]
 [88 22 32 44 16]]


In [49]:
#array dimension
print(c.shape)


(5, 5)


In [51]:
#number of dimensions
print(c.ndim)

2


In [52]:
#number of elements in an array

print(c.size)

25


In [53]:
#checking the data type of the values in the array

print(c.dtype)

int64


Mathematical operations on np array

In [54]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)     #concatenate or join two list


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[3 1 4]
 [8 0 8]
 [0 3 0]]
[[12 14 13]
 [17 12 11]
 [14 12 18]]


In [57]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 15 17]
 [25 12 19]
 [14 15 18]]
[[ -9 -13  -9]
 [ -9 -12  -3]
 [-14  -9 -18]]
[[ 36  14  52]
 [136   0  88]
 [  0  36   0]]
[[0.25       0.07142857 0.30769231]
 [0.47058824 0.         0.72727273]
 [0.         0.25       0.        ]]


In [58]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [60]:
print(np.add(a,b))

print(np.subtract(a,b))

print(np.multiply(a,b))

print(np.divide(a,b))

[[18 11 17]
 [20 25 14]
 [22 23 20]]
[[-10  -9 -11]
 [ -2  -7 -14]
 [-14 -13 -14]]
[[ 56  10  42]
 [ 99 144   0]
 [ 72  90  51]]
[[0.28571429 0.1        0.21428571]
 [0.81818182 0.5625     0.        ]
 [0.22222222 0.27777778 0.17647059]]


Array Manipulation

In [61]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 5 8]
 [2 1 4]]
(2, 3)


In [63]:
#transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 2]
 [5 1]
 [8 4]]
(3, 2)


In [64]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 8 5]
 [9 0 2]]
(2, 3)


In [65]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 9]
 [8 0]
 [5 2]]
(3, 2)


In [66]:
#reshaping a array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[7 4 8]
 [7 3 4]]
(2, 3)


In [68]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 4]
 [8 7]
 [3 4]]
(3, 2)
